name: Test Workflow Trigger

on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Workflow triggered!"
